### PR TITLE
fix cevapla button cursor pointer

### LINKED ISSUE #271: Button pointer not working properly when hovering over child comment button
### Describe the bug

The pointer on the button used for sending child comments does not work properly when hovering over it. Specifically, when I hover over the button, the pointer does not appear as expected.

### Browser(s)

_No response_

### Steps to reproduce the behavior

The pointer does not appear when hovering over the "Cevapla" button, making it difficult to select and submit a child comment.

### Expected behavior

The pointer should appear as expected when hovering over the "Cevapla" button, allowing the user to easily select and submit a child comment.

### PR DESCRIPTION
**Pull request by arabacibahadir**
closes #271

### CODE REVIEW

**Comment by mertsabinov** [comment]
In my opinion, it would be better to define the cursor property for the Button component inside the kampus-ui library. This way, all the buttons used throughout the application would automatically have the cursor: pointer style applied.

**Comment by arabacibahadir** [comment]
I tried it but it didn't work, and I wasn't sure if the same style should be applied to other buttons, so I found this solution.

**Comment by arabacibahadir** [comment]
Added hover to `Button.tsx` instead of the specific button. Thanks @mertsabinov

**Review by usirin — COMMENTED** [review]
💯

**Review by usirin — APPROVED** [review]

**Pull request merged**
